### ISSUE TITLE
[Task] 메인페이지 

### ISSUE THREAD

**Issue by dbstjs95** [codestates/info-market#40]
### ISSUE
* Group:  client, server, sr
* Type: bug, feature, delete
* Detail: fix actions from client redux

### TODO
 1. [ ] 메뉴 3개
 2. [ ]  헤더에 로그인 여부에 따른 2가지 상태 구현(로그아웃, 마이페이지)
 3. [ ]  검색창(필터 2개)
 4. [ ]  top10 유료글 (더보기 -- 게시판 이동)
 5. [ ] 최신 무료글 10 (더보기 -- 게시판 이동)

### Estimated time
 Pick one
- [ ] 0.5h
- [ ] 1h
- [ ] 1.5h
- [ ] 2h
- [ ] 2.5h
- [ ] 3h

### Labels
 * Estimated time: E: 1h
 * Group: client, server
 * Sprint: Sprint__NUMBER__
 * Urgency: High, Middle, Low
